### PR TITLE
add ipython-jl

### PR DESCRIPTION
**Pull request by marius311**
Seemed a more seamless experience for Pythonistas.

### CODE REVIEW

**Comment by tkf** [comment]
I appreciate your interest for improving PyJulia.  But I'd like to minimize the interface related to `python-jl` as there would be better ways to support PyJulia in wider range of Python installations (see also https://github.com/JuliaPy/pyjulia/issues/268#issuecomment-480128107).  I hope you are not discouraged because I'm closing this.

**Comment by tkf** [comment]
BTW, checkout https://github.com/tkf/IPython.jl if you want a "better" version `python-jl -m IPython`.  I think it's strictly better than IPython for using PyJulia because you have access to both IPython and Julia REPL (plus some event loop coordination).

**Comment by marius311** [comment]
Thanks, appreciate the thoughtful response. You brought up good points about the Jupyter kernel, will reply in that issue, but here I really think you should reconsider. I totally agree `python-jl` should go away as soon as it can, but currently it does have to exist so why not just make things slightly more userfriendly where we can? Its not as if this is some API that will be hard to deprecate later, its just what people type to launch an interpreter.

**Comment by tkf** [comment]
I'm very close to implementing an "ultimate solution" #256.  Basically, the blockers are dropping Julia 0.6 support (which in turn is blocked by PyJulia 0.3 release) and new PyCall release.  Once this is implemented, the information related to `ipython-jl` would be harmful as it would misguide users.  The reason why I said I'll not get rid of `python-jl` very soon was not because `python-jl` will still be a valid solution but because to keep backward compatibility for a while.

Due to the limited resource in development, we need to focus on good solutions.  `python-jl` is not a good solution because it is impossible to make it right.  There is no guarantee that the Python environment that `python-jl` is installed in and the Python environment active inside `python-jl` session are the same.  This would be extremely confusing for people who are not familiar with how Python imports work.

**Comment by marius311** [comment]
Ok fair enough, I didn't realize the ultimate solution was so close. Looking forward to that!

**Pull request closed without merging**
