### PR TITLE
honor trailing semicolon in Julia magic to suppress return value

### PR DESCRIPTION
**Pull request by marius311**
Hopefully self explanatory title :)

### CODE REVIEW

**Comment by marius311** [comment]
Actually, there's something weird going on where it still tries to pyconvert the answer even if there's a semicolon, looking into it...

**Comment by tkf** [comment]
Hi, thanks for the fix. Can you set up https://pre-commit.com/ so that it does not fail on style check like this? https://travis-ci.org/JuliaPy/pyjulia/jobs/583925058

**Comment by tkf** [comment]
The title says WIP. Do you want to do something else here?

**Comment by KristofferC** [comment]
Maybe I am misunderstanding but `;` shouldn't, in general, do anything to the return value. It just stops something being *printed*.

**Comment by marius311** [comment]
I think you're right. I did this with cell magic in mind, but for line magic its more subtle. To be most consistent, you want `x = %julia 1` to set `x` to 1 and print 1, but `x = %julia 1;` to not print anything, but still set `x` to 1. Do you guys know if that's actually possible given the magic API? It doesn't seem immediately obvious, but I can take a look this week.

**Comment by tkf** [comment]
@KristofferC Thanks for pointing it out.  I didn't notice this subtlety.

Note that IPython treats `;` to mean "not returning this value":

```
In [1]: "hello"
Out[1]: 'hello'

In [2]: "world";

In [3]: print(_)
hello

In [4]: 1 in Out
Out[4]: True

In [5]: 2 in Out
Out[5]: False
```

unlike Julia:

```
julia> "hello"
"hello"

julia> "world";

julia> println(ans)
world
```

I think the question is what `;` at the end of IPython cell magic should mean.  Does it mean IPython's `;` or Julia's `;`?  I think treating `;` as in this PR for the cell magic is most practical option because the printing is handled by IPython in this case and following IPython's convention sounds reasonable.

> To be most consistent, you want `x = %julia 1` to set `x` to 1 and print 1, but `x = %julia 1;` to not print anything, but still set `x` to 1. Do you guys know if that's actually possible given the magic API?

@marius311 I don't know how to do this. My guess is it would be a very hacky solution.  Maybe the safest option would be to not do any `;` handling in the line magic.  People can always write

```
x = %julia 1
None
```

**Pull request merged**
