### PR TITLE
Update release instructions and bump to 0.1.4

### PR DESCRIPTION
**Pull request by Carreau**
Hi all, 

The author of https://github.com/JuliaPy/pyjulia/issues/118 (@madeleineudell) contacted me asking if I can release – as I am the one with creds on PyPI. As usual, happy to also give access to anyone else admin on this repo requesting for it. 

So here is the head of what I'm going to release if this is ok. It would be nice to merge it and tag it for consistency (I can't, dont' have the rights on the repo).

If this get no answer I'll publish anyway in a couple of days to make it easy for contributors.

### CODE REVIEW

**Comment by madeleineudell** [comment]
@Carreau , thanks!

May I ask your view on whether pip installing pyjulia ought ever to install julia itself? As a package developer, I'd like to be able to have users install my python package without needing to install julia manually (or even, for them to think about the fact that the backend is in julia).

**Comment by Carreau** [comment]
I would suggest reading [this blog post](http://www.curiousefficiency.org/posts/2016/09/python-packaging-ecosystem.html) from Nick Coghlan (core CPython dev). 

Having pip install other programming languages (or shared binaries) is a complex problem, and this is better suited for distribution and package manager of distributions (like conda, if you are a datascientist, apt if you are a linux guru, ... ).  You can try to bend pip in order to install Julia but there will certainly be a lot of pains if you try. 

On the jupyter side we tried to happer pip into install js package from npm, and it was not a great story; So I would advise against it at least for now.

**Comment by Carreau** [comment]
Uploaded to PyPI:
https://pypi.python.org/pypi/julia

**Comment by stevengj** [comment]
See also https://github.com/tkf/conda-julia .... would be nice to have `conda add pyjulia`.

**Comment by Carreau** [comment]
We should be able to request a pyjulia-feedstock on conda-forge.

**Pull request merged**
