### PR TITLE
Fix PyJulia on Julia 1.9

### LINKED ISSUE #522: PyCall.jl setting incorrect libpython on Julia 1.9
I can't seem to get PyJulia working on Julia 1.9 (beta 4), although it works fine on 1.8.5. It seems to be some issue with the Python interpreter and libpython set by PyCall.jl. It could be interference from Conda.jl's installed copy of Python and libpython?

First, I set up a completely fresh Julia install with juliaup (note that this code will delete your `~/.julia` folder, only saving `startup.jl`):

```bash
mv ~/.julia/config/startup.jl ~/startup.jl && \
    rm -rf ~/.julia && \
    mkdir -p ~/.julia/config && \
    mv ~/startup.jl ~/.julia/config/startup.jl && \
    juliaup add 1.9 && \
    juliaup default 1.9 && \
    julia --startup-file=no -e 'using Pkg; Pkg.add(["OhMyREPL", "Revise"])'
```

Then, I run:

```bash
python -c 'import julia; julia.install()'
```
Which succeeds. However, when I try to start Julia via PyJulia:

```bash
python -c 'from julia import Main'
```

<details><summary> despite the exact same set of environment variables as used in the `install`, this fails: </summary>

```bash
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 672, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 632, in _load_backward_compatible
  File "/Users/mcranmer/venvs/main/lib/python3.10/site-packages/julia/core.py", line 247, in load_module
    JuliaMainModule(self, fullname))
  File "/Users/mcranmer/venvs/main/lib/python3.10/site-packages/julia/core.py", line 149, in __init__
    self._julia = loader.julia
  File "/Users/mcranmer/venvs/main/lib/python3.10/site-packages/julia/core.py", line 239, in julia
    self.__class__.julia = julia = Julia()
  File "/Users/mcranmer/venvs/main/lib/python3.10/site-packages/julia/core.py", line 489, in __init__
    raise UnsupportedPythonError(jlinfo)
julia.core.UnsupportedPythonError: It seems your Julia and PyJulia setup are not supported.

Julia executable:
    julia
Python interpreter and libpython used by PyCall.jl:
    /Users/mcranmer/.julia/conda/3/aarch64/bin/python
    /Users/mcranmer/.julia/conda/3/aarch64/lib/libpython3.10.dylib
Python interpreter used to import PyJulia and its libpython.
    /Users/mcranmer/venvs/main/bin/python
    /opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/Python

In Julia >= 0.7, above two paths to `libpython` have to match exactly
in order for PyJulia to work out-of-the-box.  To configure PyCall.jl to use
Python interpreter "/Users/mcranmer/venvs/main/bin/python",
run the following code in the Python REPL:

    >>> import julia
    >>> julia.install()

For more information, see:

    https://pyjulia.readthedocs.io/en/latest/troubleshooting.html
```

</details>

In particular, the Python interpreter and libpython seem to be set incorrectly:

```
Python interpreter and libpython used by PyCall.jl:
    /Users/mcranmer/.julia/conda/3/aarch64/bin/python
    /Users/mcranmer/.julia/conda/3/aarch64/lib/libpython3.10.dylib
Python interpreter used to import PyJulia and its libpython.
    /Users/mcranmer/venvs/main/bin/python
    /opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/Python
```

I'm assuming these new `python` and `libpython` are packaged by the `PyCall.jl` install. But I think ideally we would want them to be set by the user from their Python/libpython, for compatibility with Python libraries, right?

**I can run this entire workflow with `juliaup add 1.8 && juliaup default 1.8` instead, and it works fine.**

cc @mkitti @ngam @stevengj @marius311 

---

edit: I should mention I'm not using conda at all. This is a homebrew-installed version of Python running in a virtualenv.

### PR DESCRIPTION
**Pull request by MilesCranmer**
This fixes #522 with the solution discussed in the thread. Julia 1.9 introduces a breaking change to how CLI flags are parsed: https://github.com/JuliaLang/julia/pull/45335, so the `install.jl` script was parsing its arguments incorrectly. This fixes it and also adds 1.9 testing.

### CODE REVIEW

**Comment by mkitti** [comment]
What's the first argument then?

The alternative fix would be to change how install.jl is invoked, right?

**Comment by MilesCranmer** [comment]
The first argument is `--`. According to https://github.com/JuliaLang/julia/pull/45335:


> If -- appears after a non-option argument, it is preserved in ARGS. This -- has no effect on option processing since it's already stopped on the first non-option argument.

Although I'm not sure it completely works here (?) because the command is:
```
julia --startup-file=no --color=yes /Users/mcranmer/venvs/main/lib/python3.10/site-packages/julia-0.6.0-py3.10.egg/julia/install.jl -- install /Users/mcranmer/venvs/main/bin/python /opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/Python
```
yet `--` gets parsed as the first element of `ARGS`. @KristofferC is this the intended behavior or maybe a bug?

**Comment by mkitti** [comment]
```
$ julia --help

    julia [switches] -- [programfile] [args...]
```

So the `--` is in the wrong place. It should go before install.jl, not after it.

**Comment by mkitti** [comment]
It should be

```
julia --startup-file=no --color=yes -- /Users/mcranmer/venvs/main/lib/python3.10/site-packages/julia-0.6.0-py3.10.egg/julia/install.jl install /Users/mcranmer/venvs/main/bin/python /opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/Python
```

**Comment by MilesCranmer** [comment]
That makes sense. Will fix. Btw, how do I add CI testing for 1.9? Tried `1.9-nightly` too but it didn't work.

**Comment by MilesCranmer** [comment]
Cool. Just confirmed locally that it fixes #522 completely.

**Comment by mkitti** [comment]
Maybe `1.9.0-beta4` ?

**Comment by MilesCranmer** [comment]
Great, that's it, thanks. So once that test passes, I'll remove those CI changes (because those version names are temporary), and we can just merge that argument ordering fix.

**Comment by MilesCranmer** [comment]
I'm not sure what the 1.0 errors are though... Any idea?

**Comment by mkitti** [comment]
Hmm, I guess it did not work. I think 1.0 was aborted after the 1.9 did not work.

**Comment by MilesCranmer** [comment]
Okay it looks like the only errors now are for Julia 1.0. So I propose we just raise that to 1.4, matching PyCall.jl, and then merge.

**Comment by MilesCranmer** [comment]
All tests passing. Removing 1.9.0-beta4 tests until the stable version is released.

**Comment by MilesCranmer** [comment]
Awesome, thanks! How do we release versions here again? Do we just push a tag?

**Comment by mkitti** [comment]
I think there is a Github action setup

**Pull request merged**
