### PR TITLE
Update setup actions and get working on 3.12

### PR DESCRIPTION
**Pull request by MilesCranmer**
This PR tries to fix the CI setting issues in #538, #539, #540. Those PRs can then set this branch to their base.

It also merges the Python 3.12 fix from #538.

### CODE REVIEW

**Comment by MilesCranmer** [comment]
@mkitti @moelf any idea what this error is from? I haven't seen it before in the CI.

```
ERROR: Unable to dlopen(cxxpath) in parent!
Message: /lib/x86_64-linux-gnu/libstdc++.so.6�: cannot open shared object file: No such file or directory
```

does it require a specific additional library installed?

I wonder if it's related to that issue we debugged a while back in PyCall.jl: https://github.com/JuliaPy/PyCall.jl/pull/1040

**Comment by Moelf** [comment]
is it possible it's related to Github updated Ubuntu base version? But I don't understand why other Python and Julia combo don't error

**Comment by mkitti** [comment]
We should add Julia 1.9 tests. I would be in favor of dropping everything else except Julia 1.6 since it is LTS.

Julia 1.4, Julia 1.7, and Julia 1.8 are no longer supported.

**Comment by MilesCranmer** [comment]
What apt library should I try to add to get the missing C++ library?

**Comment by MilesCranmer** [comment]
I've updated the CI to only test Julia 1.6, 1.9, and 1 (=1.10 currently).

It looks like that libstdc++ issue was some unrelated issue with the action runner, rather than the environment being set up incorrectly. 

The remaining issue is a randomly-occurring "error 245" which apparently is a segfault. But this doesn't appear to be caused by any of the changes in this PR so I suggest we temporarily ignore it and merge, so that we can have a working Python 3.12 version.

Is that okay with you @mkitti? I am unable to merge as I don't have the access rights (since it marks some tests as "Required" even though they aren't ran anymore). So once you are satisfied would it be possible for you to merge?

**Comment by mkitti** [comment]
This does look better. Let me re-run that one Ubuntu test.

**Comment by MilesCranmer** [comment]
Awesome, thanks!

**Comment by MilesCranmer** [comment]
How do we release the version? I see there is an action with a workflow_dispatch... Do I just trigger that?

**Comment by MilesCranmer** [comment]
Oh wait I think I figured it out. Let me try...

**Pull request merged**
